#!/usr/bin/env bash
# check-pr-automation-halt.sh — PreToolUse hook.
# Enforces the RULES.md "PR automation halt" + "No AI attribution" invariants
# against git push / gh CLI operations. Blocks (exit 2) on:
#   - push to main/release/* (protected branches; PR-required)
#   - force-push to any branch
#   - --admin bypass attempts
#   - git commit messages containing AI-attribution markers (Co-Authored-By
#     on a bot line, "Generated with", "Generated by Claude", etc.) — checked
#     on `git commit` invocations
#   - gh pr automations (comment/merge/close/review) when the PR has comments
#     from another person (halt + tell the user)
#
# Author of record is the human operator; bots (dependabot, renovate,
# coderabbit, greptile, sonar) are not "another person."
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
input="$(cat)"
tool_name="$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null || true)"
[[ "$tool_name" == "Bash" || "$tool_name" == "bash" ]] || exit 0
command="$(printf '%s' "$input" | jq -r '.tool_input.command // .command // empty' 2>/dev/null || true)"
[[ -n "$command" ]] || exit 0

block() {
  echo "BLOCKED by harness PR-automation-halt invariant (RULES.md):" >&2
  echo "  $1" >&2
  echo "  command: $command" >&2
  exit 2
}

# --- Push protection (positions 3d in hook-firing-order) ---
if printf '%s' "$command" | grep -Eq '\bgit\s+push\b'; then
  # direct push to protected branch
  if printf '%s' "$command" | grep -Eq 'git\s+push(\s+\S+){0,2}\s+(main|release/[A-Za-z0-9._/-]+|master)\b'; then
    block "direct push to protected branch (main/release/*); open a PR instead (branch_policy: feature=pr-required)."
  fi
  # force-push to anything
  if printf '%s' "$command" | grep -Eq 'git\s+push.*(--force|-f\b|--force-with-lease)'; then
    block "force-push rewrites shared history (protected invariant: no force-push)."
  fi
  # admin bypass
  if printf '%s' "$command" | grep -Eq '\-\-admin\b'; then
    block "--admin bypass is not permitted; branch protection is authoritative."
  fi
fi

# --- No AI attribution in commit messages ---
if printf '%s' "$command" | grep -Eq '\bgit\s+commit\b'; then
  # Inspect the -m message(s). Claude Code commits via -m; grep the message body.
  msg="$(printf '%s' "$command" | sed -n "s/.*-m[[:space:]]*['\"\"]\\{0,1\\}\\(.*\\)['\"\"]\\{0,1\\}/\\1/p")"
  # Also handle the multi-arg form by extracting all -m payloads.
  all_msgs="$(printf '%s' "$command" | grep -oE "(-m[[:space:]]+('[^']*'|\"[^\"]*\"))" || true)"
  combined="$msg
$all_msgs"
  if printf '%s' "$combined" | grep -Eqi 'Co-Authored-By:.*[Cc]laude|Generated with .*Claude|Generated by .*Claude|🤖|Co-Authored-By:.*Oz|Co-Authored-By:.*bot'; then
    block "AI-attribution marker in commit message (protected invariant: no-ai-attribution). Author of record is the human operator."
  fi
fi

# --- PR automation halt on human-commented PRs ---
if printf '%s' "$command" | grep -Eq '\bgh\s+pr\s+(comment|merge|close|review|ready|edit)\b'; then
  # Determine the PR number if present.
  pr="$(printf '%s' "$command" | grep -oE 'gh\s+pr\s+[a-z]+\s+([0-9]+)' | awk '{print $3}' | head -1)"
  if [[ -n "$pr" ]] && command -v gh >/dev/null 2>&1; then
    # List comments; classify author as human vs bot. Bots listed in RULES.md.
    humans="$(gh pr view "$pr" --json comments,author,reviews 2>/dev/null \
      | jq -r '
          (.comments[] | .author.login) as $c
          | (.reviews[] | .author.login) as $r
          | [$c, $r]
        ' 2>/dev/null \
      | sort -u \
      | grep -vE '^(dependabot|renovate|coderabbit|greptile|sonar|github-actions|mergify|semantic-release-bot|allcontributors)\b' \
      | grep -vE '^\[?github-actions\]?$' || true)"
    # The author of the PR itself counts as "another person" only if it is not
    # the current operator. We cannot reliably know the operator's gh identity
    # inside a hook, so we treat a PR authored by someone other than the local
    # git user as halting.
    pr_author="$(gh pr view "$pr" --json author 2>/dev/null | jq -r '.author.login' 2>/dev/null || true)"
    local_user="$(git config user.name 2>/dev/null || true)"
    if [[ -n "$humans" ]] || { [[ -n "$pr_author" ]] && [[ "$pr_author" != "$local_user" ]]; }; then
      block "PR #$pr has input from another person; PR-automation-halt invariant (RULES.md). Halt and ask the human."
    fi
  fi
fi

exit 0
