#!/usr/bin/env bash
# PreCompact hook: auto-write a handoff summary before context is compacted.
# Reads the session JSONL, extracts recent tool calls + user messages,
# writes <project>/auto/<session_id>.md (one per session, never a shared slot) so the next session resumes in 1 turn.

set -uo pipefail
command -v jq &>/dev/null || exit 0
command -v python3 &>/dev/null || exit 0

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
[[ -z "$SESSION_ID" ]] && exit 0

JSONL=$(find "$HOME/.claude/projects" -name "${SESSION_ID}.jsonl" 2>/dev/null | head -1)
[[ -z "$JSONL" || ! -f "$JSONL" ]] && exit 0

CWD=$(echo "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)
PROJ=$(cd "${CWD:-$PWD}" 2>/dev/null && "$HOME/.claude/skills/handoff/bin/handoffs" dir 2>/dev/null)
HANDOFF_DIR="${PROJ:-$HOME/.claude/handoffs/_sem-projeto}/auto"
mkdir -p "$HANDOFF_DIR"
HANDOFF_FILE="$HANDOFF_DIR/${SESSION_ID}.md"

python3 - "$JSONL" "$HANDOFF_FILE" <<'EOF'
import json, sys, os
from datetime import datetime, timezone

jsonl_path = sys.argv[1]
out_path = sys.argv[2]

turns = []
user_messages = []
tool_calls = []
files_touched = set()

try:
    with open(jsonl_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue

            ts = d.get("timestamp", "")

            # Collect user messages. Transcripts tag them "user" (this read "human" until
            # 2026-10-01, so every auto-handoff said "0 user messages"). "user" entries also
            # carry tool_result blocks and harness-injected text (<system-reminder>, command
            # tags); only the operator's own prose is a fact worth keeping.
            if d.get("type") == "user" and not d.get("isMeta") and not d.get("isCompactSummary"):
                content = d.get("message", {}).get("content", [])
                if isinstance(content, str):
                    content = [{"type": "text", "text": content}]
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        text = block.get("text", "").strip()
                        if text and not text.startswith("<"):
                            user_messages.append((ts, text[:300]))

            # Collect tool calls and the assistant's own prose (decisions, findings)
            if d.get("type") == "assistant":
                msg = d.get("message", {})
                for block in msg.get("content", []):
                    if isinstance(block, dict) and block.get("type") == "text":
                        text = block.get("text", "").strip()
                        if text:
                            turns.append((ts, text[:400]))
                    if isinstance(block, dict) and block.get("type") == "tool_use":
                        name = block.get("name", "")
                        inp = block.get("input", {})
                        fp = inp.get("file_path", "") or inp.get("path", "")
                        cmd = inp.get("command", "")
                        if fp:
                            files_touched.add(fp)
                        tool_calls.append((ts, name, fp or cmd))

except Exception as e:
    sys.exit(0)

if not user_messages and not tool_calls:
    sys.exit(0)

# Build summary
now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
recent_user = user_messages[-10:]
recent_tools = tool_calls[-20:]

lines = [
    f"# Auto-Handoff — {now}",
    f"",
    f"**Session**: `{os.path.basename(jsonl_path).replace('.jsonl', '')}`  ",
    f"**Total user messages**: {len(user_messages)}  ",
    f"**Total tool calls**: {len(tool_calls)}",
    f"",
    f"## Recent User Requests (last 10)",
    f"",
]
for ts, text in recent_user:
    short_ts = ts[:16] if ts else "unknown"
    # Escape any markdown formatting issues
    text_clean = text.replace("\n", " ").strip()
    lines.append(f"- `{short_ts}` — {text_clean}")

if turns:
    lines += [f"", f"## Last Assistant Notes (last 5)", f""]
    for ts, text in turns[-5:]:
        lines.append(f"- `{ts[:16] if ts else 'unknown'}` " + text.replace("\n", " "))

lines += [
    f"",
    f"## Recent Tool Activity (last 20 calls)",
    f"",
]
for ts, name, target in recent_tools:
    short_ts = ts[:16] if ts else "unknown"
    target_short = os.path.basename(target) if target else ""
    lines.append(f"- `{short_ts}` {name}" + (f" → `{target_short}`" if target_short else ""))

if files_touched:
    sorted_files = sorted(files_touched)[-15:]
    lines += [
        f"",
        f"## Files Touched This Session ({len(files_touched)} total, showing last 15)",
        f"",
    ]
    for fp in sorted_files:
        lines.append(f"- `{fp}`")

lines += [
    f"",
    f"---",
    f"*Auto-generated by pre-compact-summary.sh before /compact*",
    f"*Resume: read this file, then continue the task.*",
]

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Handoff written: {out_path}")
EOF

exit 0
