#!/usr/bin/env bash
# pre-compact-memory-snapshot.sh — PreCompact hook. Companion to
# pre-compact-summary.sh (which writes latest.md handoff).
#
# This hook does two additional things to stop knowledge leak at compact:
#   1. Save a timestamped copy of the handoff so we have history, not just latest.
#   2. Scan the session JSONL for explicit decision/learning markers and write
#      a discrete memory note that gets RAG-indexed by reindex-hook.
#
# Decision markers (case-insensitive, in assistant or user content):
#   - "we decided" / "decision:"
#   - "key finding:" / "the issue was"
#   - "root cause" / "discovered that"
#   - "ADR" / "captured in ADR"

set -uo pipefail
command -v python3 &>/dev/null || exit 0
command -v jq &>/dev/null || exit 0

INPUT=$(cat 2>/dev/null || true)
SID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
[ -z "$SID" ] && exit 0

JSONL=$(find "$HOME/.claude/projects" -maxdepth 2 -name "${SID}.jsonl" -type f 2>/dev/null | head -1)
[ -z "$JSONL" ] || [ ! -f "$JSONL" ] && exit 0

# 1) Save timestamped copy of latest.md if it exists
HANDOFF_DIR="$HOME/.claude/handoffs"
TS=$(date -u +%Y-%m-%dT%H-%M-%SZ)
if [ -f "$HANDOFF_DIR/latest.md" ]; then
  ARCH="$HANDOFF_DIR/archive"
  mkdir -p "$ARCH"
  cp "$HANDOFF_DIR/latest.md" "$ARCH/$TS-pre-compact.md" 2>/dev/null || true
fi

# 2) Scan session for decision markers, write memory note if any found
# Project memory dir is sibling of the session JSONL (under the project's encoded-cwd dir)
PROJECT_DIR=$(dirname "$JSONL")
MEMORY_DIR="$PROJECT_DIR/memory"
[ -d "$MEMORY_DIR" ] || mkdir -p "$MEMORY_DIR" 2>/dev/null || exit 0

NOTE=$(python3 - "$JSONL" <<'PY' 2>/dev/null || true
import json, sys, re
path = sys.argv[1]

markers = re.compile(
    r'(we (decided|chose|picked)|decision:|key finding:|the issue was|'
    r'root cause|discovered that|captured in ADR|adr [\d-]+|'
    r'kill[- ]gate|projected (savings|impact)|the meta[- ]?bug)',
    re.IGNORECASE
)

hits = []
try:
    with open(path) as f:
        for line in f:
            try: d = json.loads(line)
            except Exception: continue
            t = d.get("type")
            if t not in ("assistant", "human"): continue
            msg = d.get("message", {})
            content = msg.get("content", [])
            if isinstance(content, list):
                for b in content:
                    if isinstance(b, dict) and b.get("type") == "text":
                        text = b.get("text", "")
                    elif isinstance(b, str):
                        text = b
                    else:
                        continue
                    for sentence in re.split(r'(?<=[.!?])\s+', text):
                        if markers.search(sentence) and 30 < len(sentence) < 400:
                            hits.append((t, sentence.strip()))
except Exception:
    sys.exit(0)

if len(hits) < 2:  # need at least 2 to be worth writing
    sys.exit(0)

# Dedup near-identical
seen = set()
uniq = []
for t, s in hits:
    key = s[:80].lower()
    if key in seen: continue
    seen.add(key)
    uniq.append((t, s))

# Cap at 15
uniq = uniq[:15]
print(json.dumps(uniq))
PY
)
[ -z "$NOTE" ] && exit 0

# Write the memory note
NOTE_FILE="$MEMORY_DIR/precompact_snapshot_$TS.md"
python3 - "$NOTE_FILE" "$SID" "$NOTE" <<'PY' 2>/dev/null || true
import json, sys, os
out, sid, raw = sys.argv[1], sys.argv[2], sys.argv[3]
items = json.loads(raw)
slug = "precompact-" + os.path.basename(out).replace("precompact_snapshot_", "").replace(".md","")
lines = [
    "---",
    f"name: {slug}",
    "tags:",
    "  - type/snapshot",
    "  - status/active",
    "  - meta/auto",
    f"description: Pre-compact snapshot of decisions/findings from session {sid[:8]}",
    "metadata:",
    "  type: project",
    "---",
    "",
    f"Auto-extracted at compact time from session `{sid}`.",
    "",
    "## Decisions / findings captured",
    ""
]
for role, sentence in items:
    lines.append(f"- **[{role}]** {sentence}")
lines.append("")
lines.append("_Auto-generated by pre-compact-memory-snapshot.sh. Review and prune if not durable knowledge._")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print(out)
PY

exit 0
