#!/usr/bin/env bash
# repo-map.sh — lightweight repo map / AST skeleton for the proposer.
#
# The open gap noted in the plan: the proposer needs structural context (which
# files exist, what symbols they define, how they relate) to target edits
# correctly — but a full file dump floods context (lost-in-the-middle). This
# script produces a BOUNDED, CACHE-STABLE map: file tree + symbol index, capped
# at a byte budget so it never floods.
#
# Cross-wave basis: agentforge context SKILL, contextweaver route-prompt
# reduction, OpenClaw repo map. The map is "static" (cache-stable) input — it
# changes only when files are added/removed, so it caches well.
#
# Output: .harness/runtime/repo-map.md (human/agent-readable) +
# .harness/runtime/repo-map.json (machine-readable symbol index).
# The proposer reads this instead of grepping blind.
#
# Usage:
#   hooks/repo-map.sh              # generate/refresh the map
#   hooks/repo-map.sh --status     # print map stats
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME="$ROOT/.harness/runtime"
MAP_MD="$RUNTIME/repo-map.md"
MAP_JSON="$RUNTIME/repo-map.json"
mkdir -p "$RUNTIME"

# Byte budget for the symbol index (prevents context flooding).
BUDGET=8192

if [[ "${1:-}" == "--status" ]]; then
  [[ -f "$MAP_MD" ]] || { echo "no repo map yet; run hooks/repo-map.sh"; exit 0; }
  echo "repo-map: $MAP_MD ($(wc -c < "$MAP_MD" | tr -d ' ') bytes)"
  echo "symbol index: $MAP_JSON ($(wc -c < "$MAP_JSON" | tr -d ' ') bytes, budget=$BUDGET)"
  exit 0
fi

ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- 1. File tree (bounded, excludes noise) ----------------------------------
tree_out="$(
  fd --type f \
    --exclude node_modules --exclude .git --exclude .harness/runtime \
    --exclude '*.pyc' --exclude dist --exclude build \
    . "$ROOT" 2>/dev/null \
    | sed "s|$ROOT/||" \
    | head -200
)"

# --- 2. Symbol index (function/def/class declarations) ----------------------
# Use rg to extract declaration lines — bounded by byte budget.
symbols="$(
  rg -n --no-heading \
    '^\s*(function |def |class |export (async )?function |export const |export class )' \
    "$ROOT" 2>/dev/null \
    | grep -vE 'node_modules|\.git/|/dist/|/build/' \
    | sed "s|$ROOT/||" \
    | head -c "$BUDGET"
)"

# --- 3. Write machine-readable index -----------------------------------------
{
  printf '{"ts":"%s","file_count":%s,"symbols":"%s"}\n' \
    "$ts" \
    "$(printf '%s\n' "$tree_out" | grep -c .)" \
    "$(printf '%s' "$symbols" | jq -Rs . 2>/dev/null || echo '""')"
} > "$MAP_JSON"

# --- 4. Write human/agent-readable map --------------------------------------
{
  printf '# Repo Map — %s\n\n' "$ts"
  printf 'Generated by hooks/repo-map.sh. Bounded to prevent context flooding.\n'
  printf 'This is cache-stable "static" input — refresh only when files are added/removed.\n\n'

  printf '## File tree (top 200 files)\n\n'
  printf '```\n'
  printf '%s\n' "$tree_out"
  printf '```\n\n'

  printf '## Symbol index (functions/classes/exports, budget %s bytes)\n\n' "$BUDGET"
  printf '```\n'
  printf '%s\n' "$symbols"
  printf '```\n\n'

  printf '## Usage for the proposer\n\n'
  printf 'Read this map to find WHERE a symbol lives before proposing an edit.\n'
  printf 'Do not grep blind — use this index to target. The map is bounded so it\n'
  printf 'does not flood context (lost-in-the-middle defense).\n'
} > "$MAP_MD"

echo "repo-map written: $MAP_MD"
echo "  files indexed: $(printf '%s\n' "$tree_out" | grep -c .)"
echo "  symbol budget: $BUDGET bytes"
exit 0
