#!/usr/bin/env bash
# sessionend-memory-writer.sh — SessionEnd hook. For expensive sessions
# (>$50 estimated cost OR >500 turns), scan for decision markers and write
# a memory note. Complements pre-compact-memory-snapshot.sh which fires on
# compact; this fires on session close without compact (most short sessions).

set -uo pipefail
command -v python3 &>/dev/null || exit 0
command -v jq &>/dev/null || exit 0

INPUT=$(cat 2>/dev/null || true)
SID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
[ -z "$SID" ] && SID="${CLAUDE_CODE_SESSION_ID:-}"
[ -z "$SID" ] && exit 0

JSONL=$(find "$HOME/.claude/projects" -maxdepth 2 -name "${SID}.jsonl" -type f 2>/dev/null | head -1)
[ -z "$JSONL" ] || [ ! -f "$JSONL" ] && exit 0

# Gate: cost or turn threshold
METRICS=$(python3 - "$JSONL" <<'PY' 2>/dev/null || true
import json, sys
PRICING = {
    "sonnet": {"input": 3.00, "cache_write": 3.75, "cache_read": 0.30, "output": 15.00},
    "haiku":  {"input": 0.80, "cache_write": 1.00, "cache_read": 0.08, "output": 4.00},
    "opus":   {"input": 15.0, "cache_write": 18.75,"cache_read": 1.50, "output": 75.00},
}
def mk(m):
    m=(m or "").lower()
    return "haiku" if "haiku" in m else "opus" if "opus" in m else "sonnet"
turns=0; cost=0.0
with open(sys.argv[1]) as f:
    for line in f:
        try: d=json.loads(line)
        except: continue
        if d.get("type")!="assistant": continue
        msg=d.get("message",{}); u=msg.get("usage",{})
        if not u: continue
        turns+=1
        p=PRICING[mk(msg.get("model"))]
        cost+=(u.get("input_tokens",0)*p["input"]+u.get("cache_creation_input_tokens",0)*p["cache_write"]+u.get("cache_read_input_tokens",0)*p["cache_read"]+u.get("output_tokens",0)*p["output"])/1_000_000
print(json.dumps({"turns":turns,"cost":cost}))
PY
)
TURNS=$(echo "$METRICS" | python3 -c "import json,sys;print(json.load(sys.stdin).get('turns',0))" 2>/dev/null || echo 0)
COST=$(echo "$METRICS" | python3 -c "import json,sys;print(f\"{json.load(sys.stdin).get('cost',0):.2f}\")" 2>/dev/null || echo 0)

# Skip unless meaningful session
SKIP=1
[ "$TURNS" -gt 500 ] && SKIP=0
python3 -c "import sys; sys.exit(0 if float('$COST') >= 50 else 1)" 2>/dev/null && SKIP=0
[ "$SKIP" = "1" ] && exit 0

# Project memory dir
PROJECT_DIR=$(dirname "$JSONL")
MEMORY_DIR="$PROJECT_DIR/memory"
mkdir -p "$MEMORY_DIR" 2>/dev/null || exit 0

TS=$(date -u +%Y-%m-%dT%H-%M-%SZ)

# Extract decision markers (same logic as pre-compact-memory-snapshot)
NOTE=$(python3 - "$JSONL" <<'PY' 2>/dev/null || true
import json, sys, re
markers = re.compile(
    r'(we (decided|chose|picked)|decision:|key finding:|the issue was|'
    r'root cause|discovered that|captured in ADR|adr [\d-]+|'
    r'kill[- ]gate|projected (savings|impact)|the meta[- ]?bug)',
    re.IGNORECASE
)
hits=[]
with open(sys.argv[1]) as f:
    for line in f:
        try: d=json.loads(line)
        except: continue
        if d.get("type") not in ("assistant","human"): continue
        c=d.get("message",{}).get("content",[])
        if not isinstance(c,list): continue
        for b in c:
            text = b.get("text","") if isinstance(b,dict) and b.get("type")=="text" else (b if isinstance(b,str) else "")
            for s in re.split(r'(?<=[.!?])\s+', text):
                if markers.search(s) and 30 < len(s) < 400:
                    hits.append((d.get("type"), s.strip()))
seen=set(); uniq=[]
for t,s in hits:
    k=s[:80].lower()
    if k in seen: continue
    seen.add(k); uniq.append((t,s))
if len(uniq) < 2: sys.exit(0)
print(json.dumps(uniq[:20]))
PY
)
[ -z "$NOTE" ] && exit 0

NOTE_FILE="$MEMORY_DIR/session_end_${TS}.md"
python3 - "$NOTE_FILE" "$SID" "$TURNS" "$COST" "$NOTE" <<'PY' 2>/dev/null || true
import json, sys, os
out, sid, turns, cost, raw = sys.argv[1:6]
items = json.loads(raw)
slug = "sessionend-" + os.path.basename(out).replace("session_end_","").replace(".md","")
lines = [
    "---",
    f"name: {slug}",
    "tags:",
    "  - type/session",
    "  - status/active",
    "  - meta/auto",
    f"description: Session-end snapshot ({turns} turns, ~${cost}) — {len(items)} decision/finding markers extracted",
    "metadata:",
    "  type: project",
    "---",
    "",
    f"Auto-extracted at session close. Session `{sid}` had {turns} turns and ~${cost} estimated cost.",
    "",
    "## Decisions / findings captured",
    ""
]
for role, sentence in items:
    lines.append(f"- **[{role}]** {sentence}")
lines.append("")
lines.append("_Auto-generated by sessionend-memory-writer.sh. Review on next session; prune if not durable._")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
PY

exit 0
